const map=L.map("map",{preferCanvas:true}).setView([19.35,-99.10],11);const osm=L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:20,attribution:"OpenStreetMap",crossOrigin:true}).addTo(map);const claro=L.tileLayer("https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png",{maxZoom:20,attribution:"OpenStreetMap | CARTO",crossOrigin:true});const satelite=L.tileLayer("https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",{maxZoom:20,attribution:"Esri",crossOrigin:true});L.control.layers({OpenStreetMap:osm,"Mapa claro":claro,"Satélite":satelite},{},{collapsed:true}).addTo(map);
let escuelasData=null,alcaldiasData=null,escuelasCluster=null,escuelasLayer=null,alcaldiasLayer=null,agebLayer=null,locationMarker=null,alcaldiaColorMap={},priorityChart=null,alcaldiaChart=null;
function cleanText(v){return String(v??"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim()}function isYes(v){return cleanText(v)==="si"}function getTotal(p){return Number(p.Total_Nec??0)}function getSchoolName(p){return p.Nombre||p.NOMBRE||p.nombre||p.NOM_ESC||p.NOM_CCT||"Escuela sin nombre"}function getCCT(p){return p.CCT||p.CCT_1||p.CCT1||p.Clave||p.CLAVECCT||""}function getAlcaldia(p){return p.Alcaldia||p.ALCALDIA||p.NOMGEO||p.NOM_ALC||p.NOM_MUN||"Sin dato"}function getAlcaldiaNameFromPolygon(p){return p.Alcaldia||p.ALCALDIA||p.NOMGEO||p.NOM_ALC||p.NOM_MUN||p.NOMBRE||p.Nombre||"Sin nombre"}
function getPriority(t){t=Number(t);if(t>=22)return"muy_alta";if(t>=16)return"alta";if(t>=10)return"media";if(t>=5)return"baja";return"muy_baja"}function priorityText(t){const p=getPriority(t);return p==="muy_alta"?"Muy alta":p==="alta"?"Alta":p==="media"?"Media":p==="baja"?"Baja":"Muy baja"}function priorityColor(t){t=Number(t);if(t>=22)return"#d73027";if(t>=16)return"#fc8d59";if(t>=10)return"#ffffbf";if(t>=5)return"#91cf60";return"#1a9850"}function priorityRadius(t){t=Number(t);if(t>=22)return 12;if(t>=16)return 10;if(t>=10)return 8;if(t>=5)return 6;return 4}
function selectedPriorities(){return Array.from(document.querySelectorAll(".priorityChk:checked")).map(c=>c.value)}function selectedNeeds(){return Array.from(document.querySelectorAll(".needChk:checked")).map(c=>c.value)}
function featurePassesFilters(f){const p=f.properties||{},q=cleanText(document.getElementById("searchBox").value),alc=document.getElementById("alcaldiaFilter").value,prs=selectedPriorities(),needs=selectedNeeds();if(!prs.includes(getPriority(getTotal(p))))return false;if(alc!=="todas"&&cleanText(getAlcaldia(p))!==cleanText(alc))return false;if(q){const text=cleanText(`${getSchoolName(p)} ${getCCT(p)} ${getAlcaldia(p)}`);if(!text.includes(q))return false}for(const field of needs){if(!isYes(p[field]))return false}return true}
function createPopup(p){let needs="";Object.keys(NEED_FIELDS).forEach(f=>{const val=p[f]||"Sin dato",icon=isYes(val)?"✅":"—";needs+=`${icon} <b>${NEED_FIELDS[f]}:</b> ${val}<br>`});return `<div class="popup-title">${getSchoolName(p)}</div><b>CCT:</b> ${getCCT(p)}<br><b>Alcaldía:</b> ${getAlcaldia(p)}<br><b>Nivel:</b> ${p.Nivel_prin||"Sin dato"}<br><b>Total necesidades:</b> ${getTotal(p)}<br><b>Prioridad:</b> ${priorityText(getTotal(p))}<hr>${needs}`}
function updateStats(c){visibleCount.textContent=c.total;countMuyAlta.textContent=c.muy_alta;countAlta.textContent=c.alta;countMedia.textContent=c.media;countBaja.textContent=c.baja;countMuyBaja.textContent=c.muy_baja}
function getFilteredFeatures(){return escuelasData.features.filter(featurePassesFilters)}
function drawSchools(){if(escuelasCluster)map.removeLayer(escuelasCluster);const c={total:0,muy_alta:0,alta:0,media:0,baja:0,muy_baja:0},alcCounts={};const filtered=getFilteredFeatures();filtered.forEach(f=>{const p=f.properties||{},pr=getPriority(getTotal(p));c.total++;c[pr]++;const a=getAlcaldia(p);alcCounts[a]=(alcCounts[a]||0)+1});escuelasLayer=L.geoJSON(filtered,{pointToLayer:(f,ll)=>L.circleMarker(ll,{radius:priorityRadius(getTotal(f.properties||{})),fillColor:priorityColor(getTotal(f.properties||{})),color:"#111",weight:1,fillOpacity:.9}),onEachFeature:(f,l)=>l.bindPopup(createPopup(f.properties||{}))});escuelasCluster=L.markerClusterGroup({chunkedLoading:true,disableClusteringAtZoom:15,spiderfyOnMaxZoom:true,showCoverageOnHover:false});escuelasCluster.addLayer(escuelasLayer);updateStats(c);updateCharts(c,alcCounts);if(chkEscuelas.checked)escuelasCluster.addTo(map)}
function drawAlcaldias(data){if(alcaldiasLayer)map.removeLayer(alcaldiasLayer);const selected=alcaldiaFilter.value;const names=data.features.map(f=>getAlcaldiaNameFromPolygon(f.properties||{})).sort();names.forEach((n,i)=>alcaldiaColorMap[n]=ALCALDIA_COLORS[i%ALCALDIA_COLORS.length]);alcaldiasLayer=L.geoJSON(data,{filter:f=>selected==="todas"||cleanText(getAlcaldiaNameFromPolygon(f.properties||{}))===cleanText(selected),style:f=>{const n=getAlcaldiaNameFromPolygon(f.properties||{});return{color:"#222",weight:selected==="todas"?1:2.2,fillColor:alcaldiaColorMap[n]||"#ccc",fillOpacity:selected==="todas"?.35:.22}},onEachFeature:(f,l)=>l.bindPopup(`<b>${getAlcaldiaNameFromPolygon(f.properties||{})}</b>`)});if(chkAlcaldias.checked)alcaldiasLayer.addTo(map);updateAlcaldiaLegend(selected)}
function updateAlcaldiaLegend(selected){const div=alcaldiaLegend;div.innerHTML="";Object.keys(alcaldiaColorMap).sort().forEach(n=>{if(selected!=="todas"&&cleanText(n)!==cleanText(selected))return;const it=document.createElement("div");it.innerHTML=`<span class="square" style="background:${alcaldiaColorMap[n]}"></span>${n}`;div.appendChild(it)})}
function zoomToSelectedAlcaldia(){const selected=alcaldiaFilter.value;if(selected==="todas"){if(escuelasCluster&&escuelasCluster.getBounds().isValid())map.fitBounds(escuelasCluster.getBounds(),{padding:[25,25]});return}let sf=null;alcaldiasData.features.forEach(f=>{if(cleanText(getAlcaldiaNameFromPolygon(f.properties||{}))===cleanText(selected))sf=f});if(sf){map.fitBounds(L.geoJSON(sf).getBounds(),{padding:[25,25]})}}
function populateAlcaldiaFilter(){const s=alcaldiaFilter,names=new Set();escuelasData.features.forEach(f=>names.add(getAlcaldia(f.properties||{})));Array.from(names).sort().forEach(n=>{const o=document.createElement("option");o.value=n;o.textContent=n;s.appendChild(o)})}
function populateSearchList(){schoolList.innerHTML="";escuelasData.features.forEach(f=>{const p=f.properties||{},o=document.createElement("option");o.value=`${getSchoolName(p)} | ${getCCT(p)}`;schoolList.appendChild(o)})}
function buildNeeds(){const box=needsBox;box.innerHTML="";Object.keys(NEED_FIELDS).forEach(f=>{const lab=document.createElement("label");lab.innerHTML=`<input type="checkbox" class="needChk" value="${f}"> ${NEED_FIELDS[f]}`;box.appendChild(lab)})}
function updateCharts(c,alcCounts){const pctx=priorityChart,aCtx=alcaldiaChart;if(window._pChart)window._pChart.destroy();window._pChart=new Chart(pctx,{type:"doughnut",data:{labels:["Muy alta","Alta","Media","Baja","Muy baja"],datasets:[{data:[c.muy_alta,c.alta,c.media,c.baja,c.muy_baja],backgroundColor:["#d73027","#fc8d59","#ffffbf","#91cf60","#1a9850"]}]},options:{plugins:{legend:{position:"bottom"}},responsive:true}});const sorted=Object.entries(alcCounts).sort((a,b)=>b[1]-a[1]).slice(0,16);if(window._aChart)window._aChart.destroy();window._aChart=new Chart(aCtx,{type:"bar",data:{labels:sorted.map(x=>x[0]),datasets:[{label:"Escuelas visibles",data:sorted.map(x=>x[1]),backgroundColor:"#337ab7"}]},options:{indexAxis:"y",plugins:{legend:{display:false}},responsive:true,scales:{x:{beginAtZero:true,ticks:{precision:0}}}}})}
function refresh(zoom=false){drawSchools();drawAlcaldias(alcaldiasData);if(zoom)zoomToSelectedAlcaldia()}
buildNeeds();Promise.all([fetch(DATA_FILES.escuelas).then(r=>r.json()),fetch(DATA_FILES.alcaldias).then(r=>r.json()),fetch(DATA_FILES.ageb).then(r=>r.json()).catch(()=>null)]).then(([escuelas,alcaldias,ageb])=>{escuelasData=escuelas;alcaldiasData=alcaldias;populateAlcaldiaFilter();populateSearchList();drawAlcaldias(alcaldias);if(ageb)agebLayer=L.geoJSON(ageb,{style:{color:"#444",weight:.4,fillOpacity:0}});drawSchools();if(escuelasCluster&&escuelasCluster.getBounds().isValid())map.fitBounds(escuelasCluster.getBounds(),{padding:[25,25]})}).catch(e=>{alert("No se pudieron cargar los datos. Revisa la carpeta data.");console.error(e)});
searchBox.addEventListener("input",()=>refresh(false));alcaldiaFilter.addEventListener("change",()=>refresh(true));document.querySelectorAll(".priorityChk").forEach(c=>c.addEventListener("change",()=>refresh(false)));document.querySelectorAll(".needChk").forEach(c=>c.addEventListener("change",()=>refresh(false)));chkEscuelas.addEventListener("change",function(){if(!escuelasCluster)return;this.checked?escuelasCluster.addTo(map):map.removeLayer(escuelasCluster)});chkAlcaldias.addEventListener("change",function(){if(!alcaldiasLayer)return;this.checked?alcaldiasLayer.addTo(map):map.removeLayer(alcaldiasLayer)});chkAgeb.addEventListener("change",function(){if(!agebLayer)return;this.checked?agebLayer.addTo(map):map.removeLayer(agebLayer)});resetBtn.addEventListener("click",()=>{searchBox.value="";alcaldiaFilter.value="todas";document.querySelectorAll(".priorityChk").forEach(c=>c.checked=true);document.querySelectorAll(".needChk").forEach(c=>c.checked=false);refresh(true)});
locateBtn.addEventListener("click",()=>{if(!navigator.geolocation){alert("Tu navegador no permite geolocalización.");return}navigator.geolocation.getCurrentPosition(pos=>{const ll=[pos.coords.latitude,pos.coords.longitude];if(locationMarker)map.removeLayer(locationMarker);locationMarker=L.circleMarker(ll,{radius:8,fillColor:"#007bff",color:"#fff",weight:2,fillOpacity:.9}).addTo(map).bindPopup("Estás aquí").openPopup();map.setView(ll,15)},()=>alert("No se pudo obtener tu ubicación."))});exportBtn.addEventListener("click",()=>{html2canvas(document.body,{useCORS:true}).then(canvas=>{const a=document.createElement("a");a.download="visor_cdmx.png";a.href=canvas.toDataURL("image/png");a.click()}).catch(()=>alert("No se pudo exportar. Intenta con el mapa base claro."))});menuBtn.addEventListener("click",()=>sidebar.classList.remove("hidden"));closeBtn.addEventListener("click",()=>sidebar.classList.add("hidden"));