const map = L.map("map", { preferCanvas: true }).setView([19.35, -99.10], 11);
const osm = L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", { maxZoom: 20, attribution: "OpenStreetMap", crossOrigin: true }).addTo(map);
const claro = L.tileLayer("https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png", { maxZoom: 20, attribution: "OpenStreetMap | CARTO", crossOrigin: true });
const satelite = L.tileLayer("https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}", { maxZoom: 20, attribution: "Esri", crossOrigin: true });
L.control.layers({ "OpenStreetMap": osm, "Mapa claro": claro, "Satélite": satelite }, {}, { collapsed: true }).addTo(map);
let escuelasData=null, alcaldiasData=null, agebData=null, escuelasCluster=null, escuelasLayer=null, alcaldiasLayer=null, agebLayer=null, locationMarker=null, alcaldiaColorMap={};
function cleanText(v){return String(v??"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\./g,"").replace(/\s+/g," ").trim();}
function canonicalAlcaldia(v){const c=cleanText(v);return ALCALDIA_ALIASES[c]||c;}
function isYes(v){return cleanText(v)==="si";} function getTotal(p){return Number(p.Total_Nec??0);} function getSchoolName(p){return p.Nombre||p.NOMBRE||p.nombre||p.NOM_ESC||p.NOM_CCT||"Escuela sin nombre";} function getCCT(p){return p.CCT||p.CCT_1||p.CCT1||p.Clave||p.CLAVECCT||"";} function getAlcaldia(p){return p.Alcaldia||p.ALCALDIA||p.NOMGEO||p.NOM_ALC||p.NOM_MUN||"Sin dato";} function getAlcaldiaNameFromPolygon(p){return p.Alcaldia||p.ALCALDIA||p.NOMGEO||p.NOM_ALC||p.NOM_MUN||p.NOMBRE||p.Nombre||"Sin nombre";}
function getPriority(t){t=Number(t); if(t>=22)return"muy_alta"; if(t>=16)return"alta"; if(t>=10)return"media"; if(t>=5)return"baja"; return"muy_baja";} function priorityText(t){return {muy_alta:"Muy alta",alta:"Alta",media:"Media",baja:"Baja",muy_baja:"Muy baja"}[getPriority(t)];} function priorityColor(t){t=Number(t); if(t>=22)return"#d73027"; if(t>=16)return"#fc8d59"; if(t>=10)return"#ffffbf"; if(t>=5)return"#91cf60"; return"#1a9850";} function priorityRadius(t){t=Number(t); if(t>=22)return 12; if(t>=16)return 10; if(t>=10)return 8; if(t>=5)return 6; return 4;}
function selectedPriorities(){return Array.from(document.querySelectorAll(".priorityChk:checked")).map(c=>c.value);} function selectedNeeds(){return Array.from(document.querySelectorAll(".needChk:checked")).map(c=>c.value);}
function featurePassesFilters(f){const p=f.properties||{}, q=cleanText(document.getElementById("searchBox").value), a=document.getElementById("alcaldiaFilter").value, prs=selectedPriorities(), needs=selectedNeeds(); if(!prs.includes(getPriority(getTotal(p))))return false; if(a!=="todas" && canonicalAlcaldia(getAlcaldia(p))!==canonicalAlcaldia(a))return false; if(q){const txt=cleanText(`${getSchoolName(p)} ${getCCT(p)} ${getAlcaldia(p)}`); if(!txt.includes(q))return false;} for(const field of needs){if(!isYes(p[field]))return false;} return true;}
function createPopup(p){let html=""; Object.keys(NEED_FIELDS).forEach(f=>{const v=p[f]||"Sin dato", icon=isYes(v)?"✅":"—"; html+=`${icon} <b>${NEED_FIELDS[f]}:</b> ${v}<br>`;}); return `<div class="popup-title">${getSchoolName(p)}</div><b>CCT:</b> ${getCCT(p)}<br><b>Alcaldía:</b> ${getAlcaldia(p)}<br><b>Nivel:</b> ${p.Nivel_prin||"Sin dato"}<br><b>Total necesidades:</b> ${getTotal(p)}<br><b>Prioridad:</b> ${priorityText(getTotal(p))}<br><hr>${html}`;}
function updateStats(c){document.getElementById("visibleCount").textContent=c.total; document.getElementById("countMuyAlta").textContent=c.muy_alta; document.getElementById("countAlta").textContent=c.alta; document.getElementById("countMedia").textContent=c.media; document.getElementById("countBaja").textContent=c.baja; document.getElementById("countMuyBaja").textContent=c.muy_baja;}
function drawSchools(){if(escuelasCluster)map.removeLayer(escuelasCluster); const counts={total:0,muy_alta:0,alta:0,media:0,baja:0,muy_baja:0}; const filtered=escuelasData.features.filter(featurePassesFilters); filtered.forEach(f=>{const pr=getPriority(getTotal(f.properties||{})); counts.total++; counts[pr]++;}); escuelasLayer=L.geoJSON(filtered,{pointToLayer:(f,ll)=>L.circleMarker(ll,{radius:priorityRadius(getTotal(f.properties||{})),fillColor:priorityColor(getTotal(f.properties||{})),color:"#111",weight:1,fillOpacity:.9}),onEachFeature:(f,l)=>l.bindPopup(createPopup(f.properties||{}))}); escuelasCluster=L.markerClusterGroup({chunkedLoading:true,disableClusteringAtZoom:15,spiderfyOnMaxZoom:true,showCoverageOnHover:false}); escuelasCluster.addLayer(escuelasLayer); updateStats(counts); if(document.getElementById("chkEscuelas").checked)escuelasCluster.addTo(map);}
function drawAlcaldias(){if(alcaldiasLayer)map.removeLayer(alcaldiasLayer); const selected=document.getElementById("alcaldiaFilter").value; const names=alcaldiasData.features.map(f=>getAlcaldiaNameFromPolygon(f.properties||{})).sort(); names.forEach((n,i)=>alcaldiaColorMap[n]=ALCALDIA_COLORS[i%ALCALDIA_COLORS.length]); alcaldiasLayer=L.geoJSON(alcaldiasData,{filter:f=>selected==="todas"||canonicalAlcaldia(getAlcaldiaNameFromPolygon(f.properties||{}))===canonicalAlcaldia(selected),style:f=>{const n=getAlcaldiaNameFromPolygon(f.properties||{}); return{color:"#222",weight:selected==="todas"?1:2.2,fillColor:alcaldiaColorMap[n]||"#ccc",fillOpacity:selected==="todas"?.35:.22};},onEachFeature:(f,l)=>l.bindPopup(`<b>${getAlcaldiaNameFromPolygon(f.properties||{})}</b>`)}); if(document.getElementById("chkAlcaldias").checked)alcaldiasLayer.addTo(map); updateAlcaldiaLegend(selected);}
function drawAgeb(){if(agebLayer)map.removeLayer(agebLayer); if(!agebData)return; const selected=document.getElementById("alcaldiaFilter").value; agebLayer=L.geoJSON(agebData,{filter:f=>{if(selected==="todas")return true; const p=f.properties||{}, n=p.Alcaldia||p.ALCALDIA||p.NOMGEO||p.NOM_ALC||p.NOM_MUN||""; return !n || canonicalAlcaldia(n)===canonicalAlcaldia(selected);},style:{color:"#444",weight:.4,fillOpacity:0}}); if(document.getElementById("chkAgeb").checked)agebLayer.addTo(map);}
function updateAlcaldiaLegend(selected){const div=document.getElementById("alcaldiaLegend"); div.innerHTML=""; Object.keys(alcaldiaColorMap).sort().forEach(n=>{if(selected!=="todas"&&canonicalAlcaldia(n)!==canonicalAlcaldia(selected))return; const item=document.createElement("div"); item.innerHTML=`<span class="square" style="background:${alcaldiaColorMap[n]}"></span>${n}`; div.appendChild(item);});}
function zoomToSelectedAlcaldia(){const selected=document.getElementById("alcaldiaFilter").value; if(selected==="todas"){if(escuelasCluster&&escuelasCluster.getBounds().isValid())map.fitBounds(escuelasCluster.getBounds(),{padding:[25,25]}); return;} let sf=null; alcaldiasData.features.forEach(f=>{if(canonicalAlcaldia(getAlcaldiaNameFromPolygon(f.properties||{}))===canonicalAlcaldia(selected))sf=f;}); if(sf){const layer=L.geoJSON(sf); map.fitBounds(layer.getBounds(),{padding:[25,25]});} else if(escuelasCluster&&escuelasCluster.getBounds().isValid())map.fitBounds(escuelasCluster.getBounds(),{padding:[25,25]});}
function populateAlcaldiaFilter(){const s=document.getElementById("alcaldiaFilter"), names=new Set(); escuelasData.features.forEach(f=>names.add(getAlcaldia(f.properties||{}))); Array.from(names).sort().forEach(n=>{const o=document.createElement("option"); o.value=n; o.textContent=n; s.appendChild(o);});}
function populateSearchList(){const list=document.getElementById("schoolList"); list.innerHTML=""; escuelasData.features.forEach(f=>{const p=f.properties||{}, o=document.createElement("option"); o.value=`${getSchoolName(p)} | ${getCCT(p)}`; list.appendChild(o);});}
function refresh(zoom=false){drawSchools(); drawAlcaldias(); drawAgeb(); if(zoom)zoomToSelectedAlcaldia();}
Promise.all([fetch(DATA_FILES.escuelas).then(r=>r.json()),fetch(DATA_FILES.alcaldias).then(r=>r.json()),fetch(DATA_FILES.ageb).then(r=>r.json()).catch(()=>null)]).then(([escuelas,alcaldias,ageb])=>{escuelasData=escuelas; alcaldiasData=alcaldias; agebData=ageb; populateAlcaldiaFilter(); populateSearchList(); drawAlcaldias(); drawAgeb(); drawSchools(); if(escuelasCluster&&escuelasCluster.getBounds().isValid())map.fitBounds(escuelasCluster.getBounds(),{padding:[25,25]});}).catch(e=>{alert("No se pudieron cargar los datos. Revisa la carpeta data."); console.error(e);});
document.getElementById("searchBox").addEventListener("input",()=>refresh(false)); document.getElementById("alcaldiaFilter").addEventListener("change",()=>refresh(true)); document.querySelectorAll(".priorityChk").forEach(c=>c.addEventListener("change",()=>refresh(false))); document.querySelectorAll(".needChk").forEach(c=>c.addEventListener("change",()=>refresh(false)));
document.getElementById("chkEscuelas").addEventListener("change",function(){if(!escuelasCluster)return; this.checked?escuelasCluster.addTo(map):map.removeLayer(escuelasCluster);}); document.getElementById("chkAlcaldias").addEventListener("change",function(){if(!alcaldiasLayer)return; this.checked?alcaldiasLayer.addTo(map):map.removeLayer(alcaldiasLayer);}); document.getElementById("chkAgeb").addEventListener("change",function(){if(!agebLayer)return; this.checked?agebLayer.addTo(map):map.removeLayer(agebLayer);});
document.getElementById("resetBtn").addEventListener("click",()=>{document.getElementById("searchBox").value=""; document.getElementById("alcaldiaFilter").value="todas"; document.querySelectorAll(".priorityChk").forEach(c=>c.checked=true); document.querySelectorAll(".needChk").forEach(c=>c.checked=false); refresh(true);});
document.getElementById("locateBtn").addEventListener("click",()=>{if(!navigator.geolocation){alert("Tu navegador no permite geolocalización."); return;} navigator.geolocation.getCurrentPosition(pos=>{const ll=[pos.coords.latitude,pos.coords.longitude]; if(locationMarker)map.removeLayer(locationMarker); locationMarker=L.circleMarker(ll,{radius:8,fillColor:"#007bff",color:"#fff",weight:2,fillOpacity:.9}).addTo(map).bindPopup("Estás aquí").openPopup(); map.setView(ll,15);},()=>alert("No se pudo obtener tu ubicación."));});
document.getElementById("exportBtn").addEventListener("click",()=>{html2canvas(document.body,{useCORS:true}).then(canvas=>{const link=document.createElement("a"); link.download="visor_cdmx.png"; link.href=canvas.toDataURL("image/png"); link.click();}).catch(()=>alert("No se pudo exportar la imagen. Intenta con mapa claro."));});
const sidebar=document.getElementById("sidebar"); document.getElementById("menuBtn").addEventListener("click",()=>sidebar.classList.remove("hidden")); document.getElementById("closeBtn").addEventListener("click",()=>sidebar.classList.add("hidden"));
